name:                AdventOfCode2024
version:             0.1.0.0
github:              "githubuser/AdventOfCode2024"
license:             BSD-3-Clause
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2024 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/AdventOfCode2024#readme>

dependencies:
- base >= 4.7 && < 5
- deepseq >= 1.4.4.0
- containers >= 0.6.5.1
- text >= 1.2.4.1
- time >= 1.9.3
- process >= 1.6.13.2
- directory >= 1.3.6.0
- filepath >= 1.4.2.1
- parsec >= 3.1.14.0
- pretty >= 1.1.3.6


ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  AdventOfCode2024-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - AdventOfCode2024
  aoc-prebuild:
    main:                 Main.hs
    source-dirs:          prebuild
    dependencies:
    - AdventOfCode2024
    - directory >= 1.3.6.0
tests:
  AdventOfCode2024-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - AdventOfCode2024
